// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqN7QVJYNCZLfhtvt4UPpWFGiTjGaqdjc',
    appId: '1:577629133211:web:66af3aa4110a5c8849293e',
    messagingSenderId: '577629133211',
    projectId: 'instagram-clone-71a1c',
    authDomain: 'instagram-clone-71a1c.firebaseapp.com',
    storageBucket: 'instagram-clone-71a1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkLMtyG028nBtIxtEVXcOx2EZ6LEu6FtY',
    appId: '1:577629133211:ios:629750ff3f2a5d5d49293e',
    messagingSenderId: '577629133211',
    projectId: 'instagram-clone-71a1c',
    storageBucket: 'instagram-clone-71a1c.appspot.com',
    iosClientId: '577629133211-qiobeqmk7ibgmtttbnncogt21rc3bkh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkLMtyG028nBtIxtEVXcOx2EZ6LEu6FtY',
    appId: '1:577629133211:ios:629750ff3f2a5d5d49293e',
    messagingSenderId: '577629133211',
    projectId: 'instagram-clone-71a1c',
    storageBucket: 'instagram-clone-71a1c.appspot.com',
    iosClientId: '577629133211-qiobeqmk7ibgmtttbnncogt21rc3bkh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
